name: backyard
description: "My Backyard USA"
publish_to: "none"
version: 2.3.1+0

environment:
  flutter: ">=3.29.2 <4.0.0"
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  http: ^1.5.0

  dio: ^5.6.0
  pretty_dio_logger: ^1.3.1
  curl_logger_dio_interceptor: ^1.0.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.6
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4

  # Sign In
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  # State management
  provider: ^6.1.5+1

  mobx: ^2.3.3+1
  flutter_mobx: ^2.2.1+1
  get_it: ^7.6.7
  injectable: ^2.4.1
  auto_route: ^9.2.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  clock: ^1.1.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0

  # Data
  intl: ^0.19.0
  jiffy: ^6.2.1
  jwt_decoder: ^2.0.1
  encrypt: ^5.0.3
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  file_picker: ^10.1.9
  in_app_purchase: ^3.2.3
  internet_connection_checker_plus: ^2.5.2
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  image: ^4.5.4
  collection: ^1.18.0
  map_launcher: ^3.5.0

  # UI
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  sizer: ^3.0.5
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.1
  dotted_line: ^3.2.2
  flutter_rating_bar: ^4.0.1
  extended_image: ^10.0.1
  webview_flutter: ^4.13.0
  photo_view: ^0.15.0
  table_calendar: ^3.0.9
  circular_countdown_timer: ^0.2.3
  carousel_slider: ^5.0.0
  flutter_switch: ^0.3.2
  flutter_slidable: ^4.0.0
  google_maps_flutter: ^2.5.0
  dropdown_button2: ^2.3.9
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.2.2
  socket_io_client: ^3.1.2
  flutter_datetime_picker_plus: ^2.2.0
  month_year_picker: ^0.4.0+1
  intl_phone_field: ^3.2.0
  fluttertoast: ^8.2.12
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  persistent_bottom_nav_bar: ^6.2.1
  dotted_border: ^3.0.1
  image_cropper: ^9.1.0
  image_picker : ^1.2.0
  mask_text_input_formatter: ^2.5.0
  flutter_svg: ^2.0.6
dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Env
  flutter_flavorizr: ^2.4.1

  # Lint
  flutter_lints: ^5.0.0
  analyzer: ^6.4.1

  # Data
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mobx_codegen: ^2.7.0
  copy_with_extension_gen: ^5.0.4
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.1

  # Tests
  mockito: ^5.4.4
  covadge: ^0.0.1

  # UI
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/random/

    - assets_v2/icons/
    - assets_v2/images/
    - assets_v2/fonts/
    - assets_v2/launcher/

flavorizr:
  ide: idea
  flavors:
    stg:
      app:
        name: "[Stg]Backyard"
      android:
        applicationId: "com.app.mybackyardusa1.stg"
        firebase:
          config: ".firebase/stg/google-services.json"
      ios:
        bundleId: "com.celect.mybackyardapp.stg"
        firebase:
          config: ".firebase/stg/GoogleService-Info.plist"
    prod:
      app:
        name: "Backyard"
      android:
        applicationId: "com.app.mybackyardusa1"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "com.celect.mybackyardapp"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"

